
name: 'activity_schema'
version: '0.1.0'
config-version: 2

require-dbt-version: [">=1.0.0", "<2.0.0"]

macro-paths: ["macros"]
log-path: "logs"

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
